<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Minio" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Repository.Abstractions\Repository.Abstractions.csproj" />
    <ProjectReference Include="..\Aletheia.Foundation\Aletheia.Foundation.csproj" />
  </ItemGroup>

</Project>
